manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: stmts
      url-base: https://github.com/StMotorSpark/
  projects:
    - name: zmk
      remote: stms
      revision: mouse-ftc
      import: app/west.yml
  self:
    path: config
